set ::msgcat::header "Project-Id-Version: Pure Data\nReport-Msgid-Bugs-To: http://sourceforge.net/tracker/?group_id=55736&atid=478070\nPOT-Creation-Date: 2012-12-31 21:04-0500\nPO-Revision-Date: 2013-01-01 08:34+0000\nLast-Translator: Hans-Christoph Steiner <hans@eds.org>\nLanguage-Team: LANGUAGE <LL@li.org>\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit\nLanguage: en_GB\nPlural-Forms: nplurals=2; plural=(n != 1);\n"
::msgcat::mcset en_gb "Uncategorized" "Uncategorised"
::msgcat::mcset en_gb "file format specification, license text, etc." "file format specification, licence text, etc."
::msgcat::mcset en_gb "text of the license for this software" "text of the licence for this software"
