// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkHttp_H
#define _C_CkHttp_H
#include "chilkatDefs.h"

#include "Chilkat_C.h"

HCkHttp CkHttp_Create(void);
void CkHttp_Dispose(HCkHttp handle);
void CkHttp_getAccept(HCkHttp cHandle, HCkString retval);
void CkHttp_putAccept(HCkHttp cHandle, const char *newVal);
const char *CkHttp_ck_accept(HCkHttp cHandle);
void CkHttp_getAcceptCharset(HCkHttp cHandle, HCkString retval);
void CkHttp_putAcceptCharset(HCkHttp cHandle, const char *newVal);
const char *CkHttp_acceptCharset(HCkHttp cHandle);
void CkHttp_getAcceptLanguage(HCkHttp cHandle, HCkString retval);
void CkHttp_putAcceptLanguage(HCkHttp cHandle, const char *newVal);
const char *CkHttp_acceptLanguage(HCkHttp cHandle);
BOOL CkHttp_getAllowGzip(HCkHttp cHandle);
void CkHttp_putAllowGzip(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getAutoAddHostHeader(HCkHttp cHandle);
void CkHttp_putAutoAddHostHeader(HCkHttp cHandle, BOOL newVal);
void CkHttp_getAwsAccessKey(HCkHttp cHandle, HCkString retval);
void CkHttp_putAwsAccessKey(HCkHttp cHandle, const char *newVal);
const char *CkHttp_awsAccessKey(HCkHttp cHandle);
void CkHttp_getAwsEndpoint(HCkHttp cHandle, HCkString retval);
void CkHttp_putAwsEndpoint(HCkHttp cHandle, const char *newVal);
const char *CkHttp_awsEndpoint(HCkHttp cHandle);
void CkHttp_getAwsSecretKey(HCkHttp cHandle, HCkString retval);
void CkHttp_putAwsSecretKey(HCkHttp cHandle, const char *newVal);
const char *CkHttp_awsSecretKey(HCkHttp cHandle);
void CkHttp_getAwsSubResources(HCkHttp cHandle, HCkString retval);
void CkHttp_putAwsSubResources(HCkHttp cHandle, const char *newVal);
const char *CkHttp_awsSubResources(HCkHttp cHandle);
BOOL CkHttp_getBasicAuth(HCkHttp cHandle);
void CkHttp_putBasicAuth(HCkHttp cHandle, BOOL newVal);
void CkHttp_getBgLastErrorText(HCkHttp cHandle, HCkString retval);
const char *CkHttp_bgLastErrorText(HCkHttp cHandle);
int CkHttp_getBgPercentDone(HCkHttp cHandle);
void CkHttp_getBgResultData(HCkHttp cHandle, HCkByteData retval);
int CkHttp_getBgResultInt(HCkHttp cHandle);
void CkHttp_getBgResultString(HCkHttp cHandle, HCkString retval);
const char *CkHttp_bgResultString(HCkHttp cHandle);
BOOL CkHttp_getBgTaskFinished(HCkHttp cHandle);
BOOL CkHttp_getBgTaskRunning(HCkHttp cHandle);
BOOL CkHttp_getBgTaskSuccess(HCkHttp cHandle);
void CkHttp_getClientIpAddress(HCkHttp cHandle, HCkString retval);
void CkHttp_putClientIpAddress(HCkHttp cHandle, const char *newVal);
const char *CkHttp_clientIpAddress(HCkHttp cHandle);
int CkHttp_getConnectTimeout(HCkHttp cHandle);
void CkHttp_putConnectTimeout(HCkHttp cHandle, int newVal);
void CkHttp_getConnection(HCkHttp cHandle, HCkString retval);
void CkHttp_putConnection(HCkHttp cHandle, const char *newVal);
const char *CkHttp_connection(HCkHttp cHandle);
void CkHttp_getCookieDir(HCkHttp cHandle, HCkString retval);
void CkHttp_putCookieDir(HCkHttp cHandle, const char *newVal);
const char *CkHttp_cookieDir(HCkHttp cHandle);
void CkHttp_getDebugLogFilePath(HCkHttp cHandle, HCkString retval);
void CkHttp_putDebugLogFilePath(HCkHttp cHandle, const char *newVal);
const char *CkHttp_debugLogFilePath(HCkHttp cHandle);
int CkHttp_getDefaultFreshPeriod(HCkHttp cHandle);
void CkHttp_putDefaultFreshPeriod(HCkHttp cHandle, int newVal);
BOOL CkHttp_getDigestAuth(HCkHttp cHandle);
void CkHttp_putDigestAuth(HCkHttp cHandle, BOOL newVal);
int CkHttp_getEventLogCount(HCkHttp cHandle);
BOOL CkHttp_getFetchFromCache(HCkHttp cHandle);
void CkHttp_putFetchFromCache(HCkHttp cHandle, BOOL newVal);
void CkHttp_getFinalRedirectUrl(HCkHttp cHandle, HCkString retval);
const char *CkHttp_finalRedirectUrl(HCkHttp cHandle);
BOOL CkHttp_getFollowRedirects(HCkHttp cHandle);
void CkHttp_putFollowRedirects(HCkHttp cHandle, BOOL newVal);
int CkHttp_getFreshnessAlgorithm(HCkHttp cHandle);
void CkHttp_putFreshnessAlgorithm(HCkHttp cHandle, int newVal);
int CkHttp_getHeartbeatMs(HCkHttp cHandle);
void CkHttp_putHeartbeatMs(HCkHttp cHandle, int newVal);
BOOL CkHttp_getIgnoreMustRevalidate(HCkHttp cHandle);
void CkHttp_putIgnoreMustRevalidate(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getIgnoreNoCache(HCkHttp cHandle);
void CkHttp_putIgnoreNoCache(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getKeepEventLog(HCkHttp cHandle);
void CkHttp_putKeepEventLog(HCkHttp cHandle, BOOL newVal);
int CkHttp_getLMFactor(HCkHttp cHandle);
void CkHttp_putLMFactor(HCkHttp cHandle, int newVal);
void CkHttp_getLastContentType(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastContentType(HCkHttp cHandle);
void CkHttp_getLastErrorHtml(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastErrorHtml(HCkHttp cHandle);
void CkHttp_getLastErrorText(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastErrorText(HCkHttp cHandle);
void CkHttp_getLastErrorXml(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastErrorXml(HCkHttp cHandle);
void CkHttp_getLastHeader(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastHeader(HCkHttp cHandle);
void CkHttp_getLastModDate(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastModDate(HCkHttp cHandle);
void CkHttp_getLastResponseHeader(HCkHttp cHandle, HCkString retval);
const char *CkHttp_lastResponseHeader(HCkHttp cHandle);
int CkHttp_getLastStatus(HCkHttp cHandle);
void CkHttp_getLogin(HCkHttp cHandle, HCkString retval);
void CkHttp_putLogin(HCkHttp cHandle, const char *newVal);
const char *CkHttp_login(HCkHttp cHandle);
void CkHttp_getLoginDomain(HCkHttp cHandle, HCkString retval);
void CkHttp_putLoginDomain(HCkHttp cHandle, const char *newVal);
const char *CkHttp_loginDomain(HCkHttp cHandle);
int CkHttp_getMaxConnections(HCkHttp cHandle);
void CkHttp_putMaxConnections(HCkHttp cHandle, int newVal);
int CkHttp_getMaxFreshPeriod(HCkHttp cHandle);
void CkHttp_putMaxFreshPeriod(HCkHttp cHandle, int newVal);
unsigned long CkHttp_getMaxResponseSize(HCkHttp cHandle);
void CkHttp_putMaxResponseSize(HCkHttp cHandle, unsigned long newVal);
int CkHttp_getMaxUrlLen(HCkHttp cHandle);
void CkHttp_putMaxUrlLen(HCkHttp cHandle, int newVal);
BOOL CkHttp_getMimicFireFox(HCkHttp cHandle);
void CkHttp_putMimicFireFox(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getMimicIE(HCkHttp cHandle);
void CkHttp_putMimicIE(HCkHttp cHandle, BOOL newVal);
int CkHttp_getMinFreshPeriod(HCkHttp cHandle);
void CkHttp_putMinFreshPeriod(HCkHttp cHandle, int newVal);
BOOL CkHttp_getNegotiateAuth(HCkHttp cHandle);
void CkHttp_putNegotiateAuth(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getNtlmAuth(HCkHttp cHandle);
void CkHttp_putNtlmAuth(HCkHttp cHandle, BOOL newVal);
int CkHttp_getNumCacheLevels(HCkHttp cHandle);
void CkHttp_putNumCacheLevels(HCkHttp cHandle, int newVal);
int CkHttp_getNumCacheRoots(HCkHttp cHandle);
BOOL CkHttp_getOAuth1(HCkHttp cHandle);
void CkHttp_putOAuth1(HCkHttp cHandle, BOOL newVal);
void CkHttp_getOAuthConsumerKey(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthConsumerKey(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthConsumerKey(HCkHttp cHandle);
void CkHttp_getOAuthConsumerSecret(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthConsumerSecret(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthConsumerSecret(HCkHttp cHandle);
void CkHttp_getOAuthRealm(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthRealm(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthRealm(HCkHttp cHandle);
void CkHttp_getOAuthSigMethod(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthSigMethod(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthSigMethod(HCkHttp cHandle);
void CkHttp_getOAuthToken(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthToken(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthToken(HCkHttp cHandle);
void CkHttp_getOAuthTokenSecret(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthTokenSecret(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthTokenSecret(HCkHttp cHandle);
void CkHttp_getOAuthVerifier(HCkHttp cHandle, HCkString retval);
void CkHttp_putOAuthVerifier(HCkHttp cHandle, const char *newVal);
const char *CkHttp_oAuthVerifier(HCkHttp cHandle);
void CkHttp_getPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putPassword(HCkHttp cHandle, const char *newVal);
const char *CkHttp_password(HCkHttp cHandle);
BOOL CkHttp_getPreferIpv6(HCkHttp cHandle);
void CkHttp_putPreferIpv6(HCkHttp cHandle, BOOL newVal);
void CkHttp_getProxyAuthMethod(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyAuthMethod(HCkHttp cHandle, const char *newVal);
const char *CkHttp_proxyAuthMethod(HCkHttp cHandle);
void CkHttp_getProxyDomain(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyDomain(HCkHttp cHandle, const char *newVal);
const char *CkHttp_proxyDomain(HCkHttp cHandle);
void CkHttp_getProxyLogin(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyLogin(HCkHttp cHandle, const char *newVal);
const char *CkHttp_proxyLogin(HCkHttp cHandle);
void CkHttp_getProxyLoginDomain(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyLoginDomain(HCkHttp cHandle, const char *newVal);
const char *CkHttp_proxyLoginDomain(HCkHttp cHandle);
void CkHttp_getProxyPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putProxyPassword(HCkHttp cHandle, const char *newVal);
const char *CkHttp_proxyPassword(HCkHttp cHandle);
int CkHttp_getProxyPort(HCkHttp cHandle);
void CkHttp_putProxyPort(HCkHttp cHandle, int newVal);
int CkHttp_getReadTimeout(HCkHttp cHandle);
void CkHttp_putReadTimeout(HCkHttp cHandle, int newVal);
void CkHttp_getRedirectVerb(HCkHttp cHandle, HCkString retval);
void CkHttp_putRedirectVerb(HCkHttp cHandle, const char *newVal);
const char *CkHttp_redirectVerb(HCkHttp cHandle);
void CkHttp_getReferer(HCkHttp cHandle, HCkString retval);
void CkHttp_putReferer(HCkHttp cHandle, const char *newVal);
const char *CkHttp_referer(HCkHttp cHandle);
BOOL CkHttp_getRequireSslCertVerify(HCkHttp cHandle);
void CkHttp_putRequireSslCertVerify(HCkHttp cHandle, BOOL newVal);
void CkHttp_getRequiredContentType(HCkHttp cHandle, HCkString retval);
void CkHttp_putRequiredContentType(HCkHttp cHandle, const char *newVal);
const char *CkHttp_requiredContentType(HCkHttp cHandle);
BOOL CkHttp_getS3Ssl(HCkHttp cHandle);
void CkHttp_putS3Ssl(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getSaveCookies(HCkHttp cHandle);
void CkHttp_putSaveCookies(HCkHttp cHandle, BOOL newVal);
int CkHttp_getSendBufferSize(HCkHttp cHandle);
void CkHttp_putSendBufferSize(HCkHttp cHandle, int newVal);
BOOL CkHttp_getSendCookies(HCkHttp cHandle);
void CkHttp_putSendCookies(HCkHttp cHandle, BOOL newVal);
void CkHttp_getSessionLogFilename(HCkHttp cHandle, HCkString retval);
void CkHttp_putSessionLogFilename(HCkHttp cHandle, const char *newVal);
const char *CkHttp_sessionLogFilename(HCkHttp cHandle);
int CkHttp_getSoRcvBuf(HCkHttp cHandle);
void CkHttp_putSoRcvBuf(HCkHttp cHandle, int newVal);
int CkHttp_getSoSndBuf(HCkHttp cHandle);
void CkHttp_putSoSndBuf(HCkHttp cHandle, int newVal);
void CkHttp_getSocksHostname(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksHostname(HCkHttp cHandle, const char *newVal);
const char *CkHttp_socksHostname(HCkHttp cHandle);
void CkHttp_getSocksPassword(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksPassword(HCkHttp cHandle, const char *newVal);
const char *CkHttp_socksPassword(HCkHttp cHandle);
int CkHttp_getSocksPort(HCkHttp cHandle);
void CkHttp_putSocksPort(HCkHttp cHandle, int newVal);
void CkHttp_getSocksUsername(HCkHttp cHandle, HCkString retval);
void CkHttp_putSocksUsername(HCkHttp cHandle, const char *newVal);
const char *CkHttp_socksUsername(HCkHttp cHandle);
int CkHttp_getSocksVersion(HCkHttp cHandle);
void CkHttp_putSocksVersion(HCkHttp cHandle, int newVal);
void CkHttp_getSslProtocol(HCkHttp cHandle, HCkString retval);
void CkHttp_putSslProtocol(HCkHttp cHandle, const char *newVal);
const char *CkHttp_sslProtocol(HCkHttp cHandle);
BOOL CkHttp_getUpdateCache(HCkHttp cHandle);
void CkHttp_putUpdateCache(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getUseBgThread(HCkHttp cHandle);
void CkHttp_putUseBgThread(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getUseIEProxy(HCkHttp cHandle);
void CkHttp_putUseIEProxy(HCkHttp cHandle, BOOL newVal);
void CkHttp_getUserAgent(HCkHttp cHandle, HCkString retval);
void CkHttp_putUserAgent(HCkHttp cHandle, const char *newVal);
const char *CkHttp_userAgent(HCkHttp cHandle);
BOOL CkHttp_getUtf8(HCkHttp cHandle);
void CkHttp_putUtf8(HCkHttp cHandle, BOOL newVal);
BOOL CkHttp_getVerboseLogging(HCkHttp cHandle);
void CkHttp_putVerboseLogging(HCkHttp cHandle, BOOL newVal);
void CkHttp_getVersion(HCkHttp cHandle, HCkString retval);
const char *CkHttp_version(HCkHttp cHandle);
BOOL CkHttp_getWasRedirected(HCkHttp cHandle);
void CkHttp_AddCacheRoot(HCkHttp cHandle, const char *dir);
BOOL CkHttp_AddQuickHeader(HCkHttp cHandle, const char *headerFieldName, const char *headerFieldValue);
HCkHttpResponse CkHttp_BgResponseObject(HCkHttp cHandle);
void CkHttp_BgTaskAbort(HCkHttp cHandle);
void CkHttp_ClearBgEventLog(HCkHttp cHandle);
void CkHttp_ClearInMemoryCookies(HCkHttp cHandle);
BOOL CkHttp_CloseAllConnections(HCkHttp cHandle);
void CkHttp_DnsCacheClear(HCkHttp cHandle);
BOOL CkHttp_Download(HCkHttp cHandle, const char *url, const char *localFilePath);
BOOL CkHttp_DownloadAppend(HCkHttp cHandle, const char *url, const char *filename);
BOOL CkHttp_DownloadHash(HCkHttp cHandle, const char *url, const char *hashAlgorithm, const char *encoding, HCkString outStr);
const char *CkHttp_downloadHash(HCkHttp cHandle, const char *url, const char *hashAlgorithm, const char *encoding);
BOOL CkHttp_EventLogName(HCkHttp cHandle, int index, HCkString outStr);
const char *CkHttp_eventLogName(HCkHttp cHandle, int index);
BOOL CkHttp_EventLogValue(HCkHttp cHandle, int index, HCkString outStr);
const char *CkHttp_eventLogValue(HCkHttp cHandle, int index);
BOOL CkHttp_ExtractMetaRefreshUrl(HCkHttp cHandle, const char *htmlContent, HCkString outStr);
const char *CkHttp_extractMetaRefreshUrl(HCkHttp cHandle, const char *htmlContent);
BOOL CkHttp_GenTimeStamp(HCkHttp cHandle, HCkString outStr);
const char *CkHttp_genTimeStamp(HCkHttp cHandle);
BOOL CkHttp_GetCacheRoot(HCkHttp cHandle, int index, HCkString outStr);
const char *CkHttp_getCacheRoot(HCkHttp cHandle, int index);
BOOL CkHttp_GetCookieXml(HCkHttp cHandle, const char *domain, HCkString outStr);
const char *CkHttp_getCookieXml(HCkHttp cHandle, const char *domain);
BOOL CkHttp_GetDomain(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_getDomain(HCkHttp cHandle, const char *url);
HCkHttpResponse CkHttp_GetHead(HCkHttp cHandle, const char *url);
BOOL CkHttp_GetRequestHeader(HCkHttp cHandle, const char *name, HCkString outStr);
const char *CkHttp_getRequestHeader(HCkHttp cHandle, const char *name);
HCkCert CkHttp_GetServerSslCert(HCkHttp cHandle, const char *domain, int port);
BOOL CkHttp_GetUrlPath(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_getUrlPath(HCkHttp cHandle, const char *url);
BOOL CkHttp_HasRequestHeader(HCkHttp cHandle, const char *name);
BOOL CkHttp_IsUnlocked(HCkHttp cHandle);
BOOL CkHttp_PostBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
const char *CkHttp_postBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip);
HCkHttpResponse CkHttp_PostJson(HCkHttp cHandle, const char *url, const char *jsonText);
HCkHttpResponse CkHttp_PostJson2(HCkHttp cHandle, const char *url, const char *contentType, const char *jsonText);
HCkHttpResponse CkHttp_PostMime(HCkHttp cHandle, const char *url, const char *mime);
HCkHttpResponse CkHttp_PostUrlEncoded(HCkHttp cHandle, const char *url, HCkHttpRequest req);
HCkHttpResponse CkHttp_PostXml(HCkHttp cHandle, const char *endpointUrl, const char *xmlContent, const char *xmlCharset);
BOOL CkHttp_PutBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
const char *CkHttp_putBinary(HCkHttp cHandle, const char *url, HCkByteData byteData, const char *contentType, BOOL md5, BOOL gzip);
BOOL CkHttp_PutText(HCkHttp cHandle, const char *url, const char *textData, const char *charset, const char *contentType, BOOL md5, BOOL gzip, HCkString outStr);
const char *CkHttp_putText(HCkHttp cHandle, const char *url, const char *textData, const char *charset, const char *contentType, BOOL md5, BOOL gzip);
BOOL CkHttp_QuickDeleteStr(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_quickDeleteStr(HCkHttp cHandle, const char *url);
BOOL CkHttp_QuickGet(HCkHttp cHandle, const char *url, HCkByteData outData);
HCkHttpResponse CkHttp_QuickGetObj(HCkHttp cHandle, const char *url);
BOOL CkHttp_QuickGetStr(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_quickGetStr(HCkHttp cHandle, const char *url);
BOOL CkHttp_QuickPutStr(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_quickPutStr(HCkHttp cHandle, const char *url);
BOOL CkHttp_RemoveQuickHeader(HCkHttp cHandle, const char *headerFieldName);
void CkHttp_RemoveRequestHeader(HCkHttp cHandle, const char *name);
BOOL CkHttp_RenderGet(HCkHttp cHandle, const char *url, HCkString outStr);
const char *CkHttp_renderGet(HCkHttp cHandle, const char *url);
BOOL CkHttp_ResumeDownload(HCkHttp cHandle, const char *url, const char *targetFilename);
BOOL CkHttp_S3_CreateBucket(HCkHttp cHandle, const char *bucketPath);
BOOL CkHttp_S3_DeleteBucket(HCkHttp cHandle, const char *bucketPath);
BOOL CkHttp_S3_DeleteObject(HCkHttp cHandle, const char *bucketPath, const char *objectName);
BOOL CkHttp_S3_DownloadBytes(HCkHttp cHandle, const char *bucketPath, const char *objectName, HCkByteData outBytes);
BOOL CkHttp_S3_DownloadFile(HCkHttp cHandle, const char *bucketPath, const char *objectName, const char *localFilePath);
BOOL CkHttp_S3_DownloadString(HCkHttp cHandle, const char *bucketPath, const char *objectName, const char *charset, HCkString outStr);
const char *CkHttp_s3_DownloadString(HCkHttp cHandle, const char *bucketPath, const char *objectName, const char *charset);
int CkHttp_S3_FileExists(HCkHttp cHandle, const char *bucketPath, const char *objectName);
BOOL CkHttp_S3_ListBucketObjects(HCkHttp cHandle, const char *bucketPath, HCkString outStr);
const char *CkHttp_s3_ListBucketObjects(HCkHttp cHandle, const char *bucketPath);
BOOL CkHttp_S3_ListBuckets(HCkHttp cHandle, HCkString outStr);
const char *CkHttp_s3_ListBuckets(HCkHttp cHandle);
BOOL CkHttp_S3_UploadBytes(HCkHttp cHandle, HCkByteData contentBytes, const char *contentType, const char *bucketPath, const char *objectName);
BOOL CkHttp_S3_UploadFile(HCkHttp cHandle, const char *localFilePath, const char *contentType, const char *bucketPath, const char *objectName);
BOOL CkHttp_S3_UploadString(HCkHttp cHandle, const char *objectContent, const char *charset, const char *contentType, const char *bucketPath, const char *objectName);
BOOL CkHttp_SaveLastError(HCkHttp cHandle, const char *path);
BOOL CkHttp_SetCookieXml(HCkHttp cHandle, const char *domain, const char *cookieXml);
BOOL CkHttp_SetOAuthRsaKey(HCkHttp cHandle, HCkPrivateKey privKey);
void CkHttp_SetRequestHeader(HCkHttp cHandle, const char *headerFieldName, const char *headerFieldValue);
BOOL CkHttp_SetSslClientCert(HCkHttp cHandle, HCkCert cert);
BOOL CkHttp_SetSslClientCertPem(HCkHttp cHandle, const char *pemDataOrPath, const char *pemPassword);
BOOL CkHttp_SetSslClientCertPfx(HCkHttp cHandle, const char *pfxPath, const char *pfxPassword);
void CkHttp_SleepMs(HCkHttp cHandle, int millisec);
HCkHttpResponse CkHttp_SynchronousRequest(HCkHttp cHandle, const char *domain, int port, BOOL ssl, HCkHttpRequest req);
BOOL CkHttp_UnlockComponent(HCkHttp cHandle, const char *unlockCode);
BOOL CkHttp_UrlDecode(HCkHttp cHandle, const char *str, HCkString outStr);
const char *CkHttp_urlDecode(HCkHttp cHandle, const char *str);
BOOL CkHttp_UrlEncode(HCkHttp cHandle, const char *str, HCkString outStr);
const char *CkHttp_urlEncode(HCkHttp cHandle, const char *str);
BOOL CkHttp_XmlRpc(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn, HCkString outStr);
const char *CkHttp_xmlRpc(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn);
BOOL CkHttp_XmlRpcPut(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn, HCkString outStr);
const char *CkHttp_xmlRpcPut(HCkHttp cHandle, const char *urlEndpoint, const char *xmlIn);
#endif
