// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkSocketWH
#define _C_CkSocketWH
#include "chilkatDefs.h"

#include "Chilkat_C.h"

HCkSocketW CkSocketW_Create(void);
HCkSocketW CkSocketW_Create2(BOOL bCallbackOwned);
void CkSocketW_Dispose(HCkSocketW handle);
BOOL CkSocketW_getAsyncAcceptFinished(HCkSocketW cHandle);
void CkSocketW_getAsyncAcceptLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncAcceptLog(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncAcceptSuccess(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncConnectFinished(HCkSocketW cHandle);
void CkSocketW_getAsyncConnectLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncConnectLog(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncConnectSuccess(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncDnsFinished(HCkSocketW cHandle);
void CkSocketW_getAsyncDnsLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncDnsLog(HCkSocketW cHandle);
void CkSocketW_getAsyncDnsResult(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncDnsResult(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncDnsSuccess(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncReceiveFinished(HCkSocketW cHandle);
void CkSocketW_getAsyncReceiveLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncReceiveLog(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncReceiveSuccess(HCkSocketW cHandle);
void CkSocketW_getAsyncReceivedBytes(HCkSocketW cHandle, HCkByteData retval);
void CkSocketW_getAsyncReceivedString(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncReceivedString(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncSendFinished(HCkSocketW cHandle);
void CkSocketW_getAsyncSendLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_asyncSendLog(HCkSocketW cHandle);
BOOL CkSocketW_getAsyncSendSuccess(HCkSocketW cHandle);
BOOL CkSocketW_getBigEndian(HCkSocketW cHandle);
void CkSocketW_putBigEndian(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getClientIpAddress(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putClientIpAddress(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_clientIpAddress(HCkSocketW cHandle);
int CkSocketW_getClientPort(HCkSocketW cHandle);
void CkSocketW_putClientPort(HCkSocketW cHandle, int newVal);
int CkSocketW_getConnectFailReason(HCkSocketW cHandle);
int CkSocketW_getDebugConnectDelayMs(HCkSocketW cHandle);
void CkSocketW_putDebugConnectDelayMs(HCkSocketW cHandle, int newVal);
int CkSocketW_getDebugDnsDelayMs(HCkSocketW cHandle);
void CkSocketW_putDebugDnsDelayMs(HCkSocketW cHandle, int newVal);
void CkSocketW_getDebugLogFilePath(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putDebugLogFilePath(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_debugLogFilePath(HCkSocketW cHandle);
int CkSocketW_getElapsedSeconds(HCkSocketW cHandle);
int CkSocketW_getHeartbeatMs(HCkSocketW cHandle);
void CkSocketW_putHeartbeatMs(HCkSocketW cHandle, int newVal);
void CkSocketW_getHttpProxyAuthMethod(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putHttpProxyAuthMethod(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_httpProxyAuthMethod(HCkSocketW cHandle);
void CkSocketW_getHttpProxyDomain(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putHttpProxyDomain(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_httpProxyDomain(HCkSocketW cHandle);
void CkSocketW_getHttpProxyHostname(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putHttpProxyHostname(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_httpProxyHostname(HCkSocketW cHandle);
void CkSocketW_getHttpProxyPassword(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putHttpProxyPassword(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_httpProxyPassword(HCkSocketW cHandle);
int CkSocketW_getHttpProxyPort(HCkSocketW cHandle);
void CkSocketW_putHttpProxyPort(HCkSocketW cHandle, int newVal);
void CkSocketW_getHttpProxyUsername(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putHttpProxyUsername(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_httpProxyUsername(HCkSocketW cHandle);
BOOL CkSocketW_getIsConnected(HCkSocketW cHandle);
BOOL CkSocketW_getKeepSessionLog(HCkSocketW cHandle);
void CkSocketW_putKeepSessionLog(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getLastErrorHtml(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_lastErrorHtml(HCkSocketW cHandle);
void CkSocketW_getLastErrorText(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_lastErrorText(HCkSocketW cHandle);
void CkSocketW_getLastErrorXml(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_lastErrorXml(HCkSocketW cHandle);
BOOL CkSocketW_getLastMethodFailed(HCkSocketW cHandle);
BOOL CkSocketW_getListenIpv6(HCkSocketW cHandle);
void CkSocketW_putListenIpv6(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getLocalIpAddress(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_localIpAddress(HCkSocketW cHandle);
int CkSocketW_getLocalPort(HCkSocketW cHandle);
int CkSocketW_getMaxReadIdleMs(HCkSocketW cHandle);
void CkSocketW_putMaxReadIdleMs(HCkSocketW cHandle, int newVal);
int CkSocketW_getMaxSendIdleMs(HCkSocketW cHandle);
void CkSocketW_putMaxSendIdleMs(HCkSocketW cHandle, int newVal);
void CkSocketW_getMyIpAddress(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_myIpAddress(HCkSocketW cHandle);
int CkSocketW_getNumReceivedClientCerts(HCkSocketW cHandle);
int CkSocketW_getNumSocketsInSet(HCkSocketW cHandle);
int CkSocketW_getNumSslAcceptableClientCAs(HCkSocketW cHandle);
int CkSocketW_getObjectId(HCkSocketW cHandle);
BOOL CkSocketW_getPreferIpv6(HCkSocketW cHandle);
void CkSocketW_putPreferIpv6(HCkSocketW cHandle, BOOL newVal);
int CkSocketW_getReceivePacketSize(HCkSocketW cHandle);
void CkSocketW_putReceivePacketSize(HCkSocketW cHandle, int newVal);
int CkSocketW_getReceivedCount(HCkSocketW cHandle);
void CkSocketW_putReceivedCount(HCkSocketW cHandle, int newVal);
void CkSocketW_getRemoteIpAddress(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_remoteIpAddress(HCkSocketW cHandle);
int CkSocketW_getRemotePort(HCkSocketW cHandle);
BOOL CkSocketW_getRequireSslCertVerify(HCkSocketW cHandle);
void CkSocketW_putRequireSslCertVerify(HCkSocketW cHandle, BOOL newVal);
int CkSocketW_getSelectorIndex(HCkSocketW cHandle);
void CkSocketW_putSelectorIndex(HCkSocketW cHandle, int newVal);
int CkSocketW_getSelectorReadIndex(HCkSocketW cHandle);
void CkSocketW_putSelectorReadIndex(HCkSocketW cHandle, int newVal);
int CkSocketW_getSelectorWriteIndex(HCkSocketW cHandle);
void CkSocketW_putSelectorWriteIndex(HCkSocketW cHandle, int newVal);
int CkSocketW_getSendPacketSize(HCkSocketW cHandle);
void CkSocketW_putSendPacketSize(HCkSocketW cHandle, int newVal);
void CkSocketW_getSessionLog(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_sessionLog(HCkSocketW cHandle);
void CkSocketW_getSessionLogEncoding(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putSessionLogEncoding(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_sessionLogEncoding(HCkSocketW cHandle);
int CkSocketW_getSoRcvBuf(HCkSocketW cHandle);
void CkSocketW_putSoRcvBuf(HCkSocketW cHandle, int newVal);
BOOL CkSocketW_getSoReuseAddr(HCkSocketW cHandle);
void CkSocketW_putSoReuseAddr(HCkSocketW cHandle, BOOL newVal);
int CkSocketW_getSoSndBuf(HCkSocketW cHandle);
void CkSocketW_putSoSndBuf(HCkSocketW cHandle, int newVal);
void CkSocketW_getSocksHostname(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putSocksHostname(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_socksHostname(HCkSocketW cHandle);
void CkSocketW_getSocksPassword(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putSocksPassword(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_socksPassword(HCkSocketW cHandle);
int CkSocketW_getSocksPort(HCkSocketW cHandle);
void CkSocketW_putSocksPort(HCkSocketW cHandle, int newVal);
void CkSocketW_getSocksUsername(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putSocksUsername(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_socksUsername(HCkSocketW cHandle);
int CkSocketW_getSocksVersion(HCkSocketW cHandle);
void CkSocketW_putSocksVersion(HCkSocketW cHandle, int newVal);
BOOL CkSocketW_getSsl(HCkSocketW cHandle);
void CkSocketW_putSsl(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getSslProtocol(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putSslProtocol(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_sslProtocol(HCkSocketW cHandle);
void CkSocketW_getStringCharset(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putStringCharset(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_stringCharset(HCkSocketW cHandle);
BOOL CkSocketW_getTcpNoDelay(HCkSocketW cHandle);
void CkSocketW_putTcpNoDelay(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getUserData(HCkSocketW cHandle, HCkString retval);
void CkSocketW_putUserData(HCkSocketW cHandle, const wchar_t *newVal);
const wchar_t *CkSocketW_userData(HCkSocketW cHandle);
BOOL CkSocketW_getVerboseLogging(HCkSocketW cHandle);
void CkSocketW_putVerboseLogging(HCkSocketW cHandle, BOOL newVal);
void CkSocketW_getVersion(HCkSocketW cHandle, HCkString retval);
const wchar_t *CkSocketW_version(HCkSocketW cHandle);
HCkSocketW CkSocketW_AcceptNextConnection(HCkSocketW cHandle, int maxWaitMs);
BOOL CkSocketW_AddSslAcceptableClientCaDn(HCkSocketW cHandle, const wchar_t *certAuthDN);
void CkSocketW_AsyncAcceptAbort(HCkSocketW cHandle);
HCkSocketW CkSocketW_AsyncAcceptSocket(HCkSocketW cHandle);
BOOL CkSocketW_AsyncAcceptStart(HCkSocketW cHandle, int maxWaitMs);
void CkSocketW_AsyncConnectAbort(HCkSocketW cHandle);
BOOL CkSocketW_AsyncConnectStart(HCkSocketW cHandle, const wchar_t *hostname, int port, BOOL ssl, int maxWaitMs);
void CkSocketW_AsyncDnsAbort(HCkSocketW cHandle);
BOOL CkSocketW_AsyncDnsStart(HCkSocketW cHandle, const wchar_t *hostname, int maxWaitMs);
void CkSocketW_AsyncReceiveAbort(HCkSocketW cHandle);
BOOL CkSocketW_AsyncReceiveBytes(HCkSocketW cHandle);
BOOL CkSocketW_AsyncReceiveBytesN(HCkSocketW cHandle, unsigned long numBytes);
BOOL CkSocketW_AsyncReceiveString(HCkSocketW cHandle);
BOOL CkSocketW_AsyncReceiveToCRLF(HCkSocketW cHandle);
BOOL CkSocketW_AsyncReceiveUntilMatch(HCkSocketW cHandle, const wchar_t *matchStr);
void CkSocketW_AsyncSendAbort(HCkSocketW cHandle);
BOOL CkSocketW_AsyncSendByteData(HCkSocketW cHandle, HCkByteData data);
BOOL CkSocketW_AsyncSendBytes(HCkSocketW cHandle, HCkByteData byteData);
BOOL CkSocketW_AsyncSendString(HCkSocketW cHandle, const wchar_t *stringToSend);
BOOL CkSocketW_BindAndListen(HCkSocketW cHandle, int port, int backLog);
BOOL CkSocketW_BuildHttpGetRequest(HCkSocketW cHandle, const wchar_t *url, HCkString outStr);
const wchar_t *CkSocketW_buildHttpGetRequest(HCkSocketW cHandle, const wchar_t *url);
int CkSocketW_CheckWriteable(HCkSocketW cHandle, int maxWaitMs);
void CkSocketW_ClearSessionLog(HCkSocketW cHandle);
HCkSocketW CkSocketW_CloneSocket(HCkSocketW cHandle);
void CkSocketW_Close(HCkSocketW cHandle, int maxWaitMs);
BOOL CkSocketW_Connect(HCkSocketW cHandle, const wchar_t *hostname, int port, BOOL ssl, int maxWaitMs);
BOOL CkSocketW_ConvertFromSsl(HCkSocketW cHandle);
BOOL CkSocketW_ConvertToSsl(HCkSocketW cHandle);
void CkSocketW_DnsCacheClear(HCkSocketW cHandle);
BOOL CkSocketW_DnsLookup(HCkSocketW cHandle, const wchar_t *hostname, int maxWaitMs, HCkString outStr);
const wchar_t *CkSocketW_dnsLookup(HCkSocketW cHandle, const wchar_t *hostname, int maxWaitMs);
HCkCertW CkSocketW_GetMyCert(HCkSocketW cHandle);
HCkCertW CkSocketW_GetReceivedClientCert(HCkSocketW cHandle, int index);
BOOL CkSocketW_GetSslAcceptableClientCaDn(HCkSocketW cHandle, int index, HCkString outStr);
const wchar_t *CkSocketW_getSslAcceptableClientCaDn(HCkSocketW cHandle, int index);
HCkCertW CkSocketW_GetSslServerCert(HCkSocketW cHandle);
BOOL CkSocketW_InitSslServer(HCkSocketW cHandle, HCkCertW cert);
BOOL CkSocketW_IsUnlocked(HCkSocketW cHandle);
BOOL CkSocketW_PollDataAvailable(HCkSocketW cHandle);
BOOL CkSocketW_ReceiveBytes(HCkSocketW cHandle, HCkByteData outData);
BOOL CkSocketW_ReceiveBytesENC(HCkSocketW cHandle, const wchar_t *encodingAlg, HCkString outStr);
const wchar_t *CkSocketW_receiveBytesENC(HCkSocketW cHandle, const wchar_t *encodingAlg);
BOOL CkSocketW_ReceiveBytesN(HCkSocketW cHandle, unsigned long numBytes, HCkByteData outData);
BOOL CkSocketW_ReceiveBytesToFile(HCkSocketW cHandle, const wchar_t *appendFilename);
int CkSocketW_ReceiveCount(HCkSocketW cHandle);
BOOL CkSocketW_ReceiveNBytesENC(HCkSocketW cHandle, unsigned long numBytes, const wchar_t *encodingAlg, HCkString outStr);
const wchar_t *CkSocketW_receiveNBytesENC(HCkSocketW cHandle, unsigned long numBytes, const wchar_t *encodingAlg);
BOOL CkSocketW_ReceiveString(HCkSocketW cHandle, HCkString outStr);
const wchar_t *CkSocketW_receiveString(HCkSocketW cHandle);
BOOL CkSocketW_ReceiveStringMaxN(HCkSocketW cHandle, int maxByteCount, HCkString outStr);
const wchar_t *CkSocketW_receiveStringMaxN(HCkSocketW cHandle, int maxByteCount);
BOOL CkSocketW_ReceiveStringUntilByte(HCkSocketW cHandle, int lookForByte, HCkString outStr);
const wchar_t *CkSocketW_receiveStringUntilByte(HCkSocketW cHandle, int lookForByte);
BOOL CkSocketW_ReceiveToCRLF(HCkSocketW cHandle, HCkString outStr);
const wchar_t *CkSocketW_receiveToCRLF(HCkSocketW cHandle);
BOOL CkSocketW_ReceiveUntilByte(HCkSocketW cHandle, int lookForByte, HCkByteData outBytes);
BOOL CkSocketW_ReceiveUntilMatch(HCkSocketW cHandle, const wchar_t *matchStr, HCkString outStr);
const wchar_t *CkSocketW_receiveUntilMatch(HCkSocketW cHandle, const wchar_t *matchStr);
BOOL CkSocketW_SaveLastError(HCkSocketW cHandle, const wchar_t *path);
int CkSocketW_SelectForReading(HCkSocketW cHandle, int timeoutMs);
int CkSocketW_SelectForWriting(HCkSocketW cHandle, int timeoutMs);
BOOL CkSocketW_SendBytes(HCkSocketW cHandle, HCkByteData data);
BOOL CkSocketW_SendBytesENC(HCkSocketW cHandle, const wchar_t *encodedBytes, const wchar_t *encodingAlg);
BOOL CkSocketW_SendCount(HCkSocketW cHandle, int byteCount);
BOOL CkSocketW_SendString(HCkSocketW cHandle, const wchar_t *stringToSend);
BOOL CkSocketW_SetSslClientCert(HCkSocketW cHandle, HCkCertW cert);
BOOL CkSocketW_SetSslClientCertPem(HCkSocketW cHandle, const wchar_t *pemDataOrFilename, const wchar_t *pemPassword);
BOOL CkSocketW_SetSslClientCertPfx(HCkSocketW cHandle, const wchar_t *pfxFilename, const wchar_t *pfxPassword);
void CkSocketW_SleepMs(HCkSocketW cHandle, int millisec);
void CkSocketW_StartTiming(HCkSocketW cHandle);
BOOL CkSocketW_TakeSocket(HCkSocketW cHandle, HCkSocketW sock);
BOOL CkSocketW_UnlockComponent(HCkSocketW cHandle, const wchar_t *unlockCode);
#endif
