// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkSFtp_H
#define _C_CkSFtp_H
#include "chilkatDefs.h"

#include "Chilkat_C.h"

HCkSFtp CkSFtp_Create(void);
void CkSFtp_Dispose(HCkSFtp handle);
void CkSFtp_getAccumulateBuffer(HCkSFtp cHandle, HCkByteData retval);
void CkSFtp_getClientIdentifier(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putClientIdentifier(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_clientIdentifier(HCkSFtp cHandle);
void CkSFtp_getClientIpAddress(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putClientIpAddress(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_clientIpAddress(HCkSFtp cHandle);
int CkSFtp_getConnectTimeoutMs(HCkSFtp cHandle);
void CkSFtp_putConnectTimeoutMs(HCkSFtp cHandle, int newVal);
void CkSFtp_getDebugLogFilePath(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putDebugLogFilePath(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_debugLogFilePath(HCkSFtp cHandle);
int CkSFtp_getDisconnectCode(HCkSFtp cHandle);
void CkSFtp_getDisconnectReason(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_disconnectReason(HCkSFtp cHandle);
BOOL CkSFtp_getEnableCache(HCkSFtp cHandle);
void CkSFtp_putEnableCache(HCkSFtp cHandle, BOOL newVal);
void CkSFtp_getFilenameCharset(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putFilenameCharset(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_filenameCharset(HCkSFtp cHandle);
void CkSFtp_getForceCipher(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putForceCipher(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_forceCipher(HCkSFtp cHandle);
BOOL CkSFtp_getForceV3(HCkSFtp cHandle);
void CkSFtp_putForceV3(HCkSFtp cHandle, BOOL newVal);
int CkSFtp_getHeartbeatMs(HCkSFtp cHandle);
void CkSFtp_putHeartbeatMs(HCkSFtp cHandle, int newVal);
void CkSFtp_getHostKeyAlg(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHostKeyAlg(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_hostKeyAlg(HCkSFtp cHandle);
void CkSFtp_getHostKeyFingerprint(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_hostKeyFingerprint(HCkSFtp cHandle);
void CkSFtp_getHttpProxyAuthMethod(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHttpProxyAuthMethod(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_httpProxyAuthMethod(HCkSFtp cHandle);
void CkSFtp_getHttpProxyDomain(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHttpProxyDomain(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_httpProxyDomain(HCkSFtp cHandle);
void CkSFtp_getHttpProxyHostname(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHttpProxyHostname(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_httpProxyHostname(HCkSFtp cHandle);
void CkSFtp_getHttpProxyPassword(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHttpProxyPassword(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_httpProxyPassword(HCkSFtp cHandle);
int CkSFtp_getHttpProxyPort(HCkSFtp cHandle);
void CkSFtp_putHttpProxyPort(HCkSFtp cHandle, int newVal);
void CkSFtp_getHttpProxyUsername(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putHttpProxyUsername(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_httpProxyUsername(HCkSFtp cHandle);
int CkSFtp_getIdleTimeoutMs(HCkSFtp cHandle);
void CkSFtp_putIdleTimeoutMs(HCkSFtp cHandle, int newVal);
BOOL CkSFtp_getIncludeDotDirs(HCkSFtp cHandle);
void CkSFtp_putIncludeDotDirs(HCkSFtp cHandle, BOOL newVal);
int CkSFtp_getInitializeFailCode(HCkSFtp cHandle);
void CkSFtp_getInitializeFailReason(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_initializeFailReason(HCkSFtp cHandle);
BOOL CkSFtp_getIsConnected(HCkSFtp cHandle);
BOOL CkSFtp_getKeepSessionLog(HCkSFtp cHandle);
void CkSFtp_putKeepSessionLog(HCkSFtp cHandle, BOOL newVal);
void CkSFtp_getLastErrorHtml(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_lastErrorHtml(HCkSFtp cHandle);
void CkSFtp_getLastErrorText(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_lastErrorText(HCkSFtp cHandle);
void CkSFtp_getLastErrorXml(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_lastErrorXml(HCkSFtp cHandle);
int CkSFtp_getMaxPacketSize(HCkSFtp cHandle);
void CkSFtp_putMaxPacketSize(HCkSFtp cHandle, int newVal);
BOOL CkSFtp_getPasswordChangeRequested(HCkSFtp cHandle);
BOOL CkSFtp_getPreferIpv6(HCkSFtp cHandle);
void CkSFtp_putPreferIpv6(HCkSFtp cHandle, BOOL newVal);
BOOL CkSFtp_getPreserveDate(HCkSFtp cHandle);
void CkSFtp_putPreserveDate(HCkSFtp cHandle, BOOL newVal);
int CkSFtp_getProtocolVersion(HCkSFtp cHandle);
void CkSFtp_getSessionLog(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_sessionLog(HCkSFtp cHandle);
int CkSFtp_getSoRcvBuf(HCkSFtp cHandle);
void CkSFtp_putSoRcvBuf(HCkSFtp cHandle, int newVal);
int CkSFtp_getSoSndBuf(HCkSFtp cHandle);
void CkSFtp_putSoSndBuf(HCkSFtp cHandle, int newVal);
void CkSFtp_getSocksHostname(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putSocksHostname(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_socksHostname(HCkSFtp cHandle);
void CkSFtp_getSocksPassword(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putSocksPassword(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_socksPassword(HCkSFtp cHandle);
int CkSFtp_getSocksPort(HCkSFtp cHandle);
void CkSFtp_putSocksPort(HCkSFtp cHandle, int newVal);
void CkSFtp_getSocksUsername(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putSocksUsername(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_socksUsername(HCkSFtp cHandle);
int CkSFtp_getSocksVersion(HCkSFtp cHandle);
void CkSFtp_putSocksVersion(HCkSFtp cHandle, int newVal);
void CkSFtp_getSyncMustMatch(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putSyncMustMatch(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_syncMustMatch(HCkSFtp cHandle);
void CkSFtp_getSyncMustNotMatch(HCkSFtp cHandle, HCkString retval);
void CkSFtp_putSyncMustNotMatch(HCkSFtp cHandle, const char *newVal);
const char *CkSFtp_syncMustNotMatch(HCkSFtp cHandle);
BOOL CkSFtp_getTcpNoDelay(HCkSFtp cHandle);
void CkSFtp_putTcpNoDelay(HCkSFtp cHandle, BOOL newVal);
int CkSFtp_getUploadChunkSize(HCkSFtp cHandle);
void CkSFtp_putUploadChunkSize(HCkSFtp cHandle, int newVal);
BOOL CkSFtp_getUtcMode(HCkSFtp cHandle);
void CkSFtp_putUtcMode(HCkSFtp cHandle, BOOL newVal);
BOOL CkSFtp_getUtf8(HCkSFtp cHandle);
void CkSFtp_putUtf8(HCkSFtp cHandle, BOOL newVal);
BOOL CkSFtp_getVerboseLogging(HCkSFtp cHandle);
void CkSFtp_putVerboseLogging(HCkSFtp cHandle, BOOL newVal);
void CkSFtp_getVersion(HCkSFtp cHandle, HCkString retval);
const char *CkSFtp_version(HCkSFtp cHandle);
int CkSFtp_AccumulateBytes(HCkSFtp cHandle, const char *handle, int maxBytes);
BOOL CkSFtp_Add64(HCkSFtp cHandle, const char *n1, const char *n2, HCkString outStr);
const char *CkSFtp_add64(HCkSFtp cHandle, const char *n1, const char *n2);
BOOL CkSFtp_AuthenticatePk(HCkSFtp cHandle, const char *username, HCkSshKey privateKey);
BOOL CkSFtp_AuthenticatePw(HCkSFtp cHandle, const char *login, const char *password);
BOOL CkSFtp_AuthenticatePwPk(HCkSFtp cHandle, const char *username, const char *password, HCkSshKey privateKey);
void CkSFtp_ClearAccumulateBuffer(HCkSFtp cHandle);
void CkSFtp_ClearCache(HCkSFtp cHandle);
void CkSFtp_ClearSessionLog(HCkSFtp cHandle);
BOOL CkSFtp_CloseHandle(HCkSFtp cHandle, const char *handle);
BOOL CkSFtp_Connect(HCkSFtp cHandle, const char *domainName, int port);
BOOL CkSFtp_CopyFileAttr(HCkSFtp cHandle, const char *localFilename, const char *remoteFilename, BOOL isHandle);
BOOL CkSFtp_CreateDir(HCkSFtp cHandle, const char *path);
void CkSFtp_Disconnect(HCkSFtp cHandle);
BOOL CkSFtp_DownloadFile(HCkSFtp cHandle, const char *handle, const char *toFilename);
BOOL CkSFtp_DownloadFileByName(HCkSFtp cHandle, const char *remoteFilePath, const char *localFilePath);
BOOL CkSFtp_Eof(HCkSFtp cHandle, const char *handle);
HCkDateTime CkSFtp_GetFileCreateDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileCreateTime(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, SYSTEMTIME *outSysTime);
BOOL CkSFtp_GetFileCreateTimeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileCreateTimeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileGroup(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileGroup(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileLastAccess(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, SYSTEMTIME *outSysTime);
HCkDateTime CkSFtp_GetFileLastAccessDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileLastAccessStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileLastAccessStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileLastModified(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, SYSTEMTIME *outSysTime);
HCkDateTime CkSFtp_GetFileLastModifiedDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileLastModifiedStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileLastModifiedStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileOwner(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileOwner(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
int CkSFtp_GetFilePermissions(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
int CkSFtp_GetFileSize32(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
__int64 CkSFtp_GetFileSize64(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_GetFileSizeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle, HCkString outStr);
const char *CkSFtp_getFileSizeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bFollowLinks, BOOL bIsHandle);
BOOL CkSFtp_InitializeSftp(HCkSFtp cHandle);
BOOL CkSFtp_LastReadFailed(HCkSFtp cHandle, const char *handle);
int CkSFtp_LastReadNumBytes(HCkSFtp cHandle, const char *handle);
BOOL CkSFtp_OpenDir(HCkSFtp cHandle, const char *path, HCkString outStr);
const char *CkSFtp_openDir(HCkSFtp cHandle, const char *path);
BOOL CkSFtp_OpenFile(HCkSFtp cHandle, const char *remotePath, const char *access, const char *createDisposition, HCkString outStr);
const char *CkSFtp_openFile(HCkSFtp cHandle, const char *remotePath, const char *access, const char *createDisposition);
HCkSFtpDir CkSFtp_ReadDir(HCkSFtp cHandle, const char *handle);
BOOL CkSFtp_ReadFileBytes(HCkSFtp cHandle, const char *handle, int numBytes, HCkByteData outBytes);
BOOL CkSFtp_ReadFileBytes32(HCkSFtp cHandle, const char *handle, int offset, int numBytes, HCkByteData outBytes);
BOOL CkSFtp_ReadFileBytes64(HCkSFtp cHandle, const char *handle, __int64 offset, int numBytes, HCkByteData outBytes);
BOOL CkSFtp_ReadFileBytes64s(HCkSFtp cHandle, const char *handle, const char *offset, int numBytes, HCkByteData outBytes);
BOOL CkSFtp_ReadFileText(HCkSFtp cHandle, const char *handle, int numBytes, const char *charset, HCkString outStr);
const char *CkSFtp_readFileText(HCkSFtp cHandle, const char *handle, int numBytes, const char *charset);
BOOL CkSFtp_ReadFileText32(HCkSFtp cHandle, const char *handle, int offset, int numBytes, const char *charset, HCkString outStr);
const char *CkSFtp_readFileText32(HCkSFtp cHandle, const char *handle, int offset, int numBytes, const char *charset);
BOOL CkSFtp_ReadFileText64(HCkSFtp cHandle, const char *handle, __int64 offset, int numBytes, const char *charset, HCkString outStr);
const char *CkSFtp_readFileText64(HCkSFtp cHandle, const char *handle, __int64 offset, int numBytes, const char *charset);
BOOL CkSFtp_ReadFileText64s(HCkSFtp cHandle, const char *handle, const char *offset, int numBytes, const char *charset, HCkString outStr);
const char *CkSFtp_readFileText64s(HCkSFtp cHandle, const char *handle, const char *offset, int numBytes, const char *charset);
BOOL CkSFtp_RealPath(HCkSFtp cHandle, const char *originalPath, const char *composePath, HCkString outStr);
const char *CkSFtp_realPath(HCkSFtp cHandle, const char *originalPath, const char *composePath);
BOOL CkSFtp_RemoveDir(HCkSFtp cHandle, const char *path);
BOOL CkSFtp_RemoveFile(HCkSFtp cHandle, const char *filename);
BOOL CkSFtp_RenameFileOrDir(HCkSFtp cHandle, const char *oldPath, const char *newPath);
BOOL CkSFtp_ResumeDownloadFileByName(HCkSFtp cHandle, const char *remoteFilePath, const char *localFilePath);
BOOL CkSFtp_ResumeUploadFileByName(HCkSFtp cHandle, const char *remoteFilePath, const char *localFilePath);
BOOL CkSFtp_SaveLastError(HCkSFtp cHandle, const char *path);
BOOL CkSFtp_SetCreateDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, HCkDateTime createDateTime);
BOOL CkSFtp_SetCreateTime(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, SYSTEMTIME *createDateTime);
BOOL CkSFtp_SetCreateTimeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bIsHandle, const char *dateTimeStr);
BOOL CkSFtp_SetLastAccessDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, HCkDateTime accessDateTime);
BOOL CkSFtp_SetLastAccessTime(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, SYSTEMTIME *accessDateTime);
BOOL CkSFtp_SetLastAccessTimeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bIsHandle, const char *dateTimeStr);
BOOL CkSFtp_SetLastModifiedDt(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, HCkDateTime modifiedDateTime);
BOOL CkSFtp_SetLastModifiedTime(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, SYSTEMTIME *modifiedDateTime);
BOOL CkSFtp_SetLastModifiedTimeStr(HCkSFtp cHandle, const char *pathOrHandle, BOOL bIsHandle, const char *dateTimeStr);
BOOL CkSFtp_SetOwnerAndGroup(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, const char *owner, const char *group);
BOOL CkSFtp_SetPermissions(HCkSFtp cHandle, const char *pathOrHandle, BOOL isHandle, int permissions);
BOOL CkSFtp_SyncTreeDownload(HCkSFtp cHandle, const char *remoteRoot, const char *localRoot, int mode, BOOL recurse);
BOOL CkSFtp_SyncTreeUpload(HCkSFtp cHandle, const char *localBaseDir, const char *remoteBaseDir, int mode, BOOL bRecurse);
BOOL CkSFtp_UnlockComponent(HCkSFtp cHandle, const char *unlockCode);
BOOL CkSFtp_UploadFile(HCkSFtp cHandle, const char *handle, const char *fromFilename);
BOOL CkSFtp_UploadFileByName(HCkSFtp cHandle, const char *remoteFilePath, const char *localFilePath);
BOOL CkSFtp_WriteFileBytes(HCkSFtp cHandle, const char *handle, HCkByteData byteData);
BOOL CkSFtp_WriteFileBytes32(HCkSFtp cHandle, const char *handle, int offset, HCkByteData data);
BOOL CkSFtp_WriteFileBytes64(HCkSFtp cHandle, const char *handle, __int64 offset64, HCkByteData data);
BOOL CkSFtp_WriteFileBytes64s(HCkSFtp cHandle, const char *handle, const char *offset64, HCkByteData data);
BOOL CkSFtp_WriteFileText(HCkSFtp cHandle, const char *handle, const char *charset, const char *textData);
BOOL CkSFtp_WriteFileText32(HCkSFtp cHandle, const char *handle, int offset32, const char *charset, const char *textData);
BOOL CkSFtp_WriteFileText64(HCkSFtp cHandle, const char *handle, __int64 offset64, const char *charset, const char *textData);
BOOL CkSFtp_WriteFileText64s(HCkSFtp cHandle, const char *handle, const char *offset64, const char *charset, const char *textData);
#endif
