// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkImap_H
#define _C_CkImap_H
#include "chilkatDefs.h"

#include "Chilkat_C.h"

HCkImap CkImap_Create(void);
void CkImap_Dispose(HCkImap handle);
BOOL CkImap_getAppendSeen(HCkImap cHandle);
void CkImap_putAppendSeen(HCkImap cHandle, BOOL newVal);
int CkImap_getAppendUid(HCkImap cHandle);
void CkImap_getAuthMethod(HCkImap cHandle, HCkString retval);
void CkImap_putAuthMethod(HCkImap cHandle, const char *newVal);
const char *CkImap_authMethod(HCkImap cHandle);
void CkImap_getAuthzId(HCkImap cHandle, HCkString retval);
void CkImap_putAuthzId(HCkImap cHandle, const char *newVal);
const char *CkImap_authzId(HCkImap cHandle);
BOOL CkImap_getAutoDownloadAttachments(HCkImap cHandle);
void CkImap_putAutoDownloadAttachments(HCkImap cHandle, BOOL newVal);
BOOL CkImap_getAutoFix(HCkImap cHandle);
void CkImap_putAutoFix(HCkImap cHandle, BOOL newVal);
void CkImap_getClientIpAddress(HCkImap cHandle, HCkString retval);
void CkImap_putClientIpAddress(HCkImap cHandle, const char *newVal);
const char *CkImap_clientIpAddress(HCkImap cHandle);
int CkImap_getConnectTimeout(HCkImap cHandle);
void CkImap_putConnectTimeout(HCkImap cHandle, int newVal);
void CkImap_getConnectedToHost(HCkImap cHandle, HCkString retval);
const char *CkImap_connectedToHost(HCkImap cHandle);
void CkImap_getDebugLogFilePath(HCkImap cHandle, HCkString retval);
void CkImap_putDebugLogFilePath(HCkImap cHandle, const char *newVal);
const char *CkImap_debugLogFilePath(HCkImap cHandle);
void CkImap_getDomain(HCkImap cHandle, HCkString retval);
void CkImap_putDomain(HCkImap cHandle, const char *newVal);
const char *CkImap_domain(HCkImap cHandle);
int CkImap_getHeartbeatMs(HCkImap cHandle);
void CkImap_putHeartbeatMs(HCkImap cHandle, int newVal);
void CkImap_getHttpProxyAuthMethod(HCkImap cHandle, HCkString retval);
void CkImap_putHttpProxyAuthMethod(HCkImap cHandle, const char *newVal);
const char *CkImap_httpProxyAuthMethod(HCkImap cHandle);
void CkImap_getHttpProxyDomain(HCkImap cHandle, HCkString retval);
void CkImap_putHttpProxyDomain(HCkImap cHandle, const char *newVal);
const char *CkImap_httpProxyDomain(HCkImap cHandle);
void CkImap_getHttpProxyHostname(HCkImap cHandle, HCkString retval);
void CkImap_putHttpProxyHostname(HCkImap cHandle, const char *newVal);
const char *CkImap_httpProxyHostname(HCkImap cHandle);
void CkImap_getHttpProxyPassword(HCkImap cHandle, HCkString retval);
void CkImap_putHttpProxyPassword(HCkImap cHandle, const char *newVal);
const char *CkImap_httpProxyPassword(HCkImap cHandle);
int CkImap_getHttpProxyPort(HCkImap cHandle);
void CkImap_putHttpProxyPort(HCkImap cHandle, int newVal);
void CkImap_getHttpProxyUsername(HCkImap cHandle, HCkString retval);
void CkImap_putHttpProxyUsername(HCkImap cHandle, const char *newVal);
const char *CkImap_httpProxyUsername(HCkImap cHandle);
BOOL CkImap_getKeepSessionLog(HCkImap cHandle);
void CkImap_putKeepSessionLog(HCkImap cHandle, BOOL newVal);
void CkImap_getLastAppendedMime(HCkImap cHandle, HCkString retval);
const char *CkImap_lastAppendedMime(HCkImap cHandle);
void CkImap_getLastCommand(HCkImap cHandle, HCkString retval);
const char *CkImap_lastCommand(HCkImap cHandle);
void CkImap_getLastErrorHtml(HCkImap cHandle, HCkString retval);
const char *CkImap_lastErrorHtml(HCkImap cHandle);
void CkImap_getLastErrorText(HCkImap cHandle, HCkString retval);
const char *CkImap_lastErrorText(HCkImap cHandle);
void CkImap_getLastErrorXml(HCkImap cHandle, HCkString retval);
const char *CkImap_lastErrorXml(HCkImap cHandle);
void CkImap_getLastIntermediateResponse(HCkImap cHandle, HCkString retval);
const char *CkImap_lastIntermediateResponse(HCkImap cHandle);
void CkImap_getLastResponse(HCkImap cHandle, HCkString retval);
const char *CkImap_lastResponse(HCkImap cHandle);
void CkImap_getLoggedInUser(HCkImap cHandle, HCkString retval);
const char *CkImap_loggedInUser(HCkImap cHandle);
int CkImap_getNumMessages(HCkImap cHandle);
BOOL CkImap_getPeekMode(HCkImap cHandle);
void CkImap_putPeekMode(HCkImap cHandle, BOOL newVal);
int CkImap_getPort(HCkImap cHandle);
void CkImap_putPort(HCkImap cHandle, int newVal);
BOOL CkImap_getPreferIpv6(HCkImap cHandle);
void CkImap_putPreferIpv6(HCkImap cHandle, BOOL newVal);
int CkImap_getReadTimeout(HCkImap cHandle);
void CkImap_putReadTimeout(HCkImap cHandle, int newVal);
BOOL CkImap_getRequireSslCertVerify(HCkImap cHandle);
void CkImap_putRequireSslCertVerify(HCkImap cHandle, BOOL newVal);
void CkImap_getSearchCharset(HCkImap cHandle, HCkString retval);
void CkImap_putSearchCharset(HCkImap cHandle, const char *newVal);
const char *CkImap_searchCharset(HCkImap cHandle);
void CkImap_getSelectedMailbox(HCkImap cHandle, HCkString retval);
const char *CkImap_selectedMailbox(HCkImap cHandle);
int CkImap_getSendBufferSize(HCkImap cHandle);
void CkImap_putSendBufferSize(HCkImap cHandle, int newVal);
char CkImap_getSeparatorChar(HCkImap cHandle);
void CkImap_putSeparatorChar(HCkImap cHandle, char newVal);
void CkImap_getSessionLog(HCkImap cHandle, HCkString retval);
const char *CkImap_sessionLog(HCkImap cHandle);
int CkImap_getSoRcvBuf(HCkImap cHandle);
void CkImap_putSoRcvBuf(HCkImap cHandle, int newVal);
int CkImap_getSoSndBuf(HCkImap cHandle);
void CkImap_putSoSndBuf(HCkImap cHandle, int newVal);
void CkImap_getSocksHostname(HCkImap cHandle, HCkString retval);
void CkImap_putSocksHostname(HCkImap cHandle, const char *newVal);
const char *CkImap_socksHostname(HCkImap cHandle);
void CkImap_getSocksPassword(HCkImap cHandle, HCkString retval);
void CkImap_putSocksPassword(HCkImap cHandle, const char *newVal);
const char *CkImap_socksPassword(HCkImap cHandle);
int CkImap_getSocksPort(HCkImap cHandle);
void CkImap_putSocksPort(HCkImap cHandle, int newVal);
void CkImap_getSocksUsername(HCkImap cHandle, HCkString retval);
void CkImap_putSocksUsername(HCkImap cHandle, const char *newVal);
const char *CkImap_socksUsername(HCkImap cHandle);
int CkImap_getSocksVersion(HCkImap cHandle);
void CkImap_putSocksVersion(HCkImap cHandle, int newVal);
BOOL CkImap_getSsl(HCkImap cHandle);
void CkImap_putSsl(HCkImap cHandle, BOOL newVal);
void CkImap_getSslProtocol(HCkImap cHandle, HCkString retval);
void CkImap_putSslProtocol(HCkImap cHandle, const char *newVal);
const char *CkImap_sslProtocol(HCkImap cHandle);
BOOL CkImap_getSslServerCertVerified(HCkImap cHandle);
BOOL CkImap_getStartTls(HCkImap cHandle);
void CkImap_putStartTls(HCkImap cHandle, BOOL newVal);
int CkImap_getUidNext(HCkImap cHandle);
int CkImap_getUidValidity(HCkImap cHandle);
BOOL CkImap_getUtf8(HCkImap cHandle);
void CkImap_putUtf8(HCkImap cHandle, BOOL newVal);
BOOL CkImap_getVerboseLogging(HCkImap cHandle);
void CkImap_putVerboseLogging(HCkImap cHandle, BOOL newVal);
void CkImap_getVersion(HCkImap cHandle, HCkString retval);
const char *CkImap_version(HCkImap cHandle);
BOOL CkImap_AddPfxSourceData(HCkImap cHandle, HCkByteData pfxBytes, const char *pfxPassword);
BOOL CkImap_AddPfxSourceFile(HCkImap cHandle, const char *pfxFilePath, const char *pfxPassword);
BOOL CkImap_AppendMail(HCkImap cHandle, const char *mailbox, HCkEmail email);
BOOL CkImap_AppendMime(HCkImap cHandle, const char *mailbox, const char *mimeText);
BOOL CkImap_AppendMimeWithDate(HCkImap cHandle, const char *mailbox, const char *mimeText, SYSTEMTIME *internalDate);
BOOL CkImap_AppendMimeWithDateStr(HCkImap cHandle, const char *mailbox, const char *mimeText, const char *internalDateStr);
BOOL CkImap_AppendMimeWithFlags(HCkImap cHandle, const char *mailbox, const char *mimeText, BOOL seen, BOOL flagged, BOOL answered, BOOL draft);
BOOL CkImap_Capability(HCkImap cHandle, HCkString outStr);
const char *CkImap_capability(HCkImap cHandle);
HCkMessageSet CkImap_CheckForNewEmail(HCkImap cHandle);
void CkImap_ClearSessionLog(HCkImap cHandle);
BOOL CkImap_CloseMailbox(HCkImap cHandle, const char *mailbox);
BOOL CkImap_Connect(HCkImap cHandle, const char *domainName);
BOOL CkImap_Copy(HCkImap cHandle, int msgId, BOOL bUid, const char *copyToMailbox);
BOOL CkImap_CopyMultiple(HCkImap cHandle, HCkMessageSet messageSet, const char *copyToMailbox);
BOOL CkImap_CopySequence(HCkImap cHandle, int startSeqNum, int count, const char *copyToMailbox);
BOOL CkImap_CreateMailbox(HCkImap cHandle, const char *mailbox);
BOOL CkImap_DeleteMailbox(HCkImap cHandle, const char *mailbox);
BOOL CkImap_Disconnect(HCkImap cHandle);
BOOL CkImap_ExamineMailbox(HCkImap cHandle, const char *mailbox);
BOOL CkImap_Expunge(HCkImap cHandle);
BOOL CkImap_ExpungeAndClose(HCkImap cHandle);
BOOL CkImap_FetchAttachment(HCkImap cHandle, HCkEmail emailObject, int attachmentIndex, const char *saveToPath);
BOOL CkImap_FetchAttachmentBytes(HCkImap cHandle, HCkEmail email, int attachIndex, HCkByteData outBytes);
BOOL CkImap_FetchAttachmentString(HCkImap cHandle, HCkEmail emailObject, int attachmentIndex, const char *charset, HCkString outStr);
const char *CkImap_fetchAttachmentString(HCkImap cHandle, HCkEmail emailObject, int attachmentIndex, const char *charset);
HCkEmailBundle CkImap_FetchBundle(HCkImap cHandle, HCkMessageSet messageSet);
HCkStringArray CkImap_FetchBundleAsMime(HCkImap cHandle, HCkMessageSet messageSet);
HCkEmailBundle CkImap_FetchChunk(HCkImap cHandle, int startSeqNum, int count, HCkMessageSet failedSet, HCkMessageSet fetchedSet);
BOOL CkImap_FetchFlags(HCkImap cHandle, int msgId, BOOL bUid, HCkString outStrFlags);
const char *CkImap_fetchFlags(HCkImap cHandle, int msgId, BOOL bUid);
HCkEmailBundle CkImap_FetchHeaders(HCkImap cHandle, HCkMessageSet messageSet);
HCkEmailBundle CkImap_FetchSequence(HCkImap cHandle, int startSeqNum, int numMessages);
HCkStringArray CkImap_FetchSequenceAsMime(HCkImap cHandle, int startSeqNum, int numMessages);
HCkEmailBundle CkImap_FetchSequenceHeaders(HCkImap cHandle, int startSeqNum, int numMessages);
HCkEmail CkImap_FetchSingle(HCkImap cHandle, int msgId, BOOL bUid);
BOOL CkImap_FetchSingleAsMime(HCkImap cHandle, int msgId, BOOL bUid, HCkString outStrMime);
const char *CkImap_fetchSingleAsMime(HCkImap cHandle, int msgId, BOOL bUid);
HCkEmail CkImap_FetchSingleHeader(HCkImap cHandle, int msgId, BOOL bUid);
BOOL CkImap_FetchSingleHeaderAsMime(HCkImap cHandle, int msgId, BOOL bUID, HCkString outStr);
const char *CkImap_fetchSingleHeaderAsMime(HCkImap cHandle, int msgId, BOOL bUID);
HCkMessageSet CkImap_GetAllUids(HCkImap cHandle);
BOOL CkImap_GetMailAttachFilename(HCkImap cHandle, HCkEmail email, int attachIndex, HCkString outStrFilename);
const char *CkImap_getMailAttachFilename(HCkImap cHandle, HCkEmail email, int attachIndex);
int CkImap_GetMailAttachSize(HCkImap cHandle, HCkEmail email, int attachIndex);
int CkImap_GetMailFlag(HCkImap cHandle, HCkEmail email, const char *flagName);
int CkImap_GetMailNumAttach(HCkImap cHandle, HCkEmail email);
int CkImap_GetMailSize(HCkImap cHandle, HCkEmail email);
HCkCert CkImap_GetSslServerCert(HCkImap cHandle);
BOOL CkImap_IdleCheck(HCkImap cHandle, int timeoutMs, HCkString outStr);
const char *CkImap_idleCheck(HCkImap cHandle, int timeoutMs);
BOOL CkImap_IdleDone(HCkImap cHandle);
BOOL CkImap_IdleStart(HCkImap cHandle);
BOOL CkImap_IsConnected(HCkImap cHandle);
BOOL CkImap_IsLoggedIn(HCkImap cHandle);
BOOL CkImap_IsUnlocked(HCkImap cHandle);
HCkMailboxes CkImap_ListMailboxes(HCkImap cHandle, const char *reference, const char *wildcardedMailbox);
HCkMailboxes CkImap_ListSubscribed(HCkImap cHandle, const char *reference, const char *wildcardedMailbox);
BOOL CkImap_Login(HCkImap cHandle, const char *login, const char *password);
BOOL CkImap_Logout(HCkImap cHandle);
BOOL CkImap_Noop(HCkImap cHandle);
BOOL CkImap_RefetchMailFlags(HCkImap cHandle, HCkEmail email);
BOOL CkImap_RenameMailbox(HCkImap cHandle, const char *fromMailbox, const char *toMailbox);
BOOL CkImap_SaveLastError(HCkImap cHandle, const char *path);
HCkMessageSet CkImap_Search(HCkImap cHandle, const char *criteria, BOOL bUid);
BOOL CkImap_SelectMailbox(HCkImap cHandle, const char *mailbox);
BOOL CkImap_SendRawCommand(HCkImap cHandle, const char *cmd, HCkString outRawResponse);
const char *CkImap_sendRawCommand(HCkImap cHandle, const char *cmd);
BOOL CkImap_SendRawCommandB(HCkImap cHandle, const char *cmd, HCkByteData outBytes);
BOOL CkImap_SendRawCommandC(HCkImap cHandle, HCkByteData cmd, HCkByteData outBytes);
#if defined(CK_CSP_INCLUDED)
BOOL CkImap_SetCSP(HCkImap cHandle, HCkCsp csp);
#endif
BOOL CkImap_SetDecryptCert(HCkImap cHandle, HCkCert cert);
BOOL CkImap_SetDecryptCert2(HCkImap cHandle, HCkCert cert, HCkPrivateKey key);
BOOL CkImap_SetFlag(HCkImap cHandle, int msgId, BOOL bUid, const char *flagName, int value);
BOOL CkImap_SetFlags(HCkImap cHandle, HCkMessageSet messageSet, const char *flagName, int value);
BOOL CkImap_SetMailFlag(HCkImap cHandle, HCkEmail email, const char *flagName, int value);
BOOL CkImap_SetSslClientCert(HCkImap cHandle, HCkCert cert);
BOOL CkImap_SetSslClientCertPem(HCkImap cHandle, const char *pemDataOrFilename, const char *pemPassword);
BOOL CkImap_SetSslClientCertPfx(HCkImap cHandle, const char *pfxFilename, const char *pfxPassword);
BOOL CkImap_SshAuthenticatePk(HCkImap cHandle, const char *sshLogin, HCkSshKey privateKey);
BOOL CkImap_SshAuthenticatePw(HCkImap cHandle, const char *sshLogin, const char *sshPassword);
BOOL CkImap_SshTunnel(HCkImap cHandle, const char *sshServerHostname, int sshPort);
BOOL CkImap_StoreFlags(HCkImap cHandle, int msgId, BOOL bUid, const char *flagNames, int value);
BOOL CkImap_Subscribe(HCkImap cHandle, const char *mailbox);
BOOL CkImap_UnlockComponent(HCkImap cHandle, const char *unlockCode);
BOOL CkImap_Unsubscribe(HCkImap cHandle, const char *mailbox);
BOOL CkImap_UseCertVault(HCkImap cHandle, HCkXmlCertVault vault);
#endif
